Working
java-park-mail-ru/PanzerElite-09-2017 pull request #5
Opened 2017-09-20 16:18 UTC by Crusader727

2017-09-20 17:54 UTC, isopov commented
1. Checkstyle добейте
2. `PanzerElite.iml` удалите
3. `.gitignore` настройте - там `target` например, нету...
4. В pom.xml как-то всё очень странно. Проект не должен зависеть от мавен-плагинов. Подключить плагин, и зависеть от него - разные вещи. И к плагинам можно подключать зависимости, которые не подключать к проекту. В общем весь верх от parent, и включая зависимости должен выглядеть как-то так:
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.7.RELEASE</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jetty</artifactId>
        </dependency>
    </dependencies>
```
На `LATEST` лучше не завязываться, а то можно "вдруг" словить поломку билда от изменения внешних причин (мажорное обновление библиотеки появилось в репозитории)
5. `org.json.JSONObject` - не используйте никогда. Со spring-boot вам приезжает Jackson - вот его и используйте. А точнее из контроллеров просто возвращайте объекты - их подхватит Messagemapper спринговый и преобразует в json.
6. `@CrossOrigin` лучше объявить один раз на контроллере, а не на каждом методе одинаковый. И `*` - это значение по-умолчанию - его можно было бы не указывать явно, и оно вам не подходит, потому что с таким разрешением нельзя будет использовать сессию.
7. `@RequestMapping(method = RequestMethod.POST..` можно заменить на `@PostMapping(...`
8.  Метод `setHttpSession` в контроллере - я не нашел где бы не выполнялся его if
9. У logout всегда пустое тело - почему же тогда это String? Можно возвращать `ResponseEntity<Void>` - и в изменении пароля тоже. Ну и при всегда пустом теле как-то странно смотрится `produces = "application/json"`
10. При выходе лучше убивать всю сессию через `httpSession.invalidate()`, а не очищать один её аттрибут.
11. Пароль вы зачем с клиента на сервер передаёте?
12. Сервис у вас зависит от http - какое-то странное разделение получается.
13. Метод `UserService.register` при попытке зарегистрировать пользователя под дублирующимся логином перезапишет его и вернет ошибку в коде ответа.
14. Пока без айдишников можно было бы вообще обойтись, но вот `idgen.getAndDecrement()` - это совсем плохо - даже с транзакциями счетчики айдишников никогда не уменьшаются - пропуски в айдишниках это вообще не проблема, а любая возможность дублирования айдишников - это огромная проблема. Почему айдишники - строки?
15. Не привыкайте писать такой неоптимальный код. Вынесите результат get в переменную. А если Map будет большая? А если это будет поход по сети в СУБД на диск?
```
if (db.get(user.getLogin()) != null) {
            db.get(user.getLogin()).setPassword(password);
            ...
}
```

2017-09-20 17:54 UTC, isopov requested changes
В комментарии замечания.

2017-09-24 18:13 UTC, isopov commented
1. System.out.println - удалите. Про логирование, вроде, Константин рассказывал в лекции:
```
private static final org.slf4j.Logger LOGGER = org.slf4j.LoggerFactory.getLogger(UserService.class);
...
LOGGER.error("foobar", err);
```
Только не логируйте с таким уровнем логирования нормальные ситуации - например, когда, пользователь с имейлом ошибся.
2. `SpringAutowiredFieldsWarningInspection` - не надо это предупреждение подавлять. Лучше всего через конструктор зависимые бины получать. И на конструкторе можно без `@Autowired`
3. `ResponseEntity` - еще остались raw-использования.
4. `@Bean`-метод в сервисе. Я удивлён, что оно вообще работает. Это надо в `@Configuration`-классе делать. При этом можно в `@SpringBootApplication`-классе - он тоже является конфигурацией.
5. вы гадость-муть в application.properties у коллег списали? Удалите нафиг. А лучше было, конечно, материал РК2 в пул-реквест для РК1 не пихать - помочь с заведением отдельной ветки и чисткой этой от ненужных коммитов? Ну или почистите до хоть какого-то удобоваримого состояния и зальем так. Зависимость на jpa, который вы не используете реально вам только мешает - лучше на `spring-boot-starter-jdbc`, и аннотации неиспользуемые с класса User поудалять.

2017-10-03 18:21 UTC, isopov commented
@Crusader727 ping

2017-10-04 14:02 UTC, Crusader727 commented
"@Bean-метод в сервисе ...", не понимаем, что это означает. Просто у нас нету такой аннотации вообще)

2017-10-04 14:31 UTC, Crusader727 commented
Autowired тоже нету, возможно вы смотрели старый коммит...

2017-10-07 13:10 UTC, Crusader727 commented
не получилось заsquashить коммиты.....

2017-10-07 13:11 UTC, isopov commented
Хотите я посквошу за вас? ))

2017-10-07 13:13 UTC, isopov approved these changes

2017-10-07 13:14 UTC, merged

2017-10-07 13:17 UTC, Crusader727 commented
Было бы здорово, если бы вы нас научили)))))))