RK2
java-park-mail-ru/PanzerElite-09-2017 pull request #8
Opened 2017-10-19 13:57 UTC by Crusader727

2017-10-23 18:05 UTC, KSolovyev commented
порешайте, пожалуйста, конфликты
Только поглядите сначала вот сюда:
https://github.com/java-park-mail-ru/PanzerElite-09-2017/network

2017-10-29 14:17 UTC, KSolovyev commented
конфликты, ребят. После этого буду смотреть

2017-10-29 16:59 UTC, Crusader727 commented
Порешали. Можно смотреть.)

2017-11-07 19:31 UTC, KSolovyev requested changes

2017-11-07 19:31 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/UserController.java
> +            return ResponseEntity.status(HttpStatus.FORBIDDEN).body("Some conflict, cant create user.");
это должен быть 400 Bad request. Сообщение должно быть в JSON. и в нем нужно что-то осмысленное

2017-11-07 19:31 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/UserController.java
> +            return ResponseEntity.status(HttpStatus.FORBIDDEN).body("Some conflict, cant create user.");
вместо проверки на null  и пустоту можно использовать что-то вроде StringUtils.isBlank()

2017-11-07 19:31 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/UserController.java
> +        httpSession.setAttribute(SESSIONKEY, body);
целесообразность вынесения одной строички в отдельный метод сомнительна. В качестве значения здесь должен быть неизменяемый инвариант. Сама моделька слабо подходит, так как пользователь может менять в ней поля между обращениями к сессисс

2017-11-07 19:31 UTC, KSolovyev commented on src/main/java/ru/mail/park/models/User.java
> +    private Integer frags;
давайте игровые изменения вынесем в отдельную ветку. Будем смотреть их позже

2017-11-07 19:31 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/UserService.java
> +@Transactional
Без аннотации `@EnableTransactionManagement` на каком-нибудь конфигурационном классе аннотация `@Transactional` не работает

2017-11-07 19:31 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/UserService.java
> +            final int five = 5;
![image](https://user-images.githubusercontent.com/4122313/32513234-ac625610-c40a-11e7-90db-211cf516c0c8.png)
подтяните новый профиль park_checker.xml из примеров, пожалуйста

2017-11-07 19:31 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/UserService.java
> +                                + "  password = COALESCE(?, password) "
а зачем здесь COALESCE?? У вас что пароль может быть  null??

2017-11-07 19:31 UTC, KSolovyev commented on src/main/resources/application.properties
> +#spring.datasource.username=docker
закомментированный код убрать

2017-11-11 10:33 UTC, KSolovyev approved these changes

2017-11-11 10:34 UTC, merged

2017-11-11 10:34 UTC, KSolovyev commented
надо будет помержить master в develop (или аналог develop'a)